"""Generate scene_filter configs for the perturbed and cross-agent (aug) datasets.

make_cache_subsets.py samples from navtrain.yaml, whose log_names are plain nuPlan log
names -- those address dataset/navsim_logs/trainval, where there is one pkl per log.
create_openscene_metadata_purturbed.py and _aug.py write one pkl per SCENE and per
(log, agent) instead, named "<log>_<hash>.pkl", so filter_scenes' first test

    dataloader.py:108  if log_pickle_path.name.replace(".pkl", "") not in scene_filter.log_names

skips every file and the cache comes out empty. This script emits filters whose
log_names are the stems actually on disk, and whose tokens are exactly the tokens
filter_scenes would key on, so the cache size is known before the job is submitted.

Two phases. --index walks a dataset root and records, per pkl, the tokens that survive
the same window logic filter_scenes applies (the index is cached as JSON and reused).
Generation then samples from that index up to a storage budget.

    python scripts/training/make_cache_subsets_rap.py --dataset perturbed --budget-gb 40
    python scripts/training/make_cache_subsets_rap.py --dataset aug       --budget-gb 60
"""

import argparse
import json
import os
import pickle
import random
from multiprocessing import Pool
from pathlib import Path

import yaml

# Measured, not assumed: cache/rap_ego is 120 GB over 14,675 token directories.
# The 9.08 in make_cache_subsets.py's header and the 8.73 in
# run_dataset_caching_perturbed.sh both run high.
MB_PER_TOKEN = 8.18

DATASETS = {
    "perturbed": "dataset_perturbed",
    "aug": "dataset_aug",
}

HEADER = """# GENERATED by scripts/training/make_cache_subsets_rap.py -- do not edit by hand.
# {dataset} cache: {n:,} of {avail:,} available tokens ({frac:.1%}), ~{gb:.0f} GB at {mb} MB/token.
# log_names are "<log>_<hash>" pkl stems under {root}/navsim_logs/{split},
# NOT plain nuPlan log names -- see this script's docstring.
"""


def _scan(path: str):
    """Tokens in one pkl that survive filter_scenes' window logic.

    Mirrors dataloader.py:106-133 exactly: fixed-size windows stepped by frame_interval,
    short tail dropped, the window's current frame is index num_history_frames-1, and
    that frame decides is_valid / has_route / token.
    """
    num_history, num_future, interval, has_route = _scan.cfg
    num_frames = num_history + num_future
    try:
        frames = pickle.load(open(path, "rb"))
    except Exception as exc:  # a truncated pkl should not kill the whole scan
        return path, [], repr(exc)

    tokens = []
    for i in range(0, len(frames), interval):
        window = frames[i: i + num_frames]
        if len(window) < num_frames:
            continue
        current = window[num_history - 1]
        if current.get("is_valid", True) is False:
            continue
        if has_route and len(current.get("roadblock_ids") or []) == 0:
            continue
        token = current.get("token")
        if token is None:
            continue  # filtered_scenes is keyed by token; a None key collapses scenes
        tokens.append(token)
    return path, tokens, None


def _init(cfg):
    _scan.cfg = cfg


def build_index(root: Path, split: str, cfg, workers: int, out: Path) -> dict:
    log_dir = root / "navsim_logs" / split
    files = sorted(str(log_dir / f) for f in os.listdir(log_dir) if f.endswith(".pkl"))
    print(f"indexing {len(files):,} pkl files in {log_dir} with {workers} workers")

    index, errors = {}, 0
    with Pool(workers, initializer=_init, initargs=(cfg,)) as pool:
        for n, (path, tokens, err) in enumerate(
            pool.imap_unordered(_scan, files, chunksize=16), 1
        ):
            if err:
                errors += 1
            elif tokens:
                index[Path(path).name[:-4]] = tokens
            if n % 2000 == 0:
                print(f"  {n:,}/{len(files):,}  stems kept {len(index):,}")

    total = sum(len(v) for v in index.values())
    print(f"indexed {len(index):,} stems, {total:,} tokens"
          + (f", {errors} unreadable" if errors else ""))
    out.write_text(json.dumps({"config": cfg, "index": index}))
    print(f"wrote {out}")
    return index


def main() -> None:
    p = argparse.ArgumentParser()
    p.add_argument("--dataset", choices=sorted(DATASETS), required=True)
    p.add_argument("--budget-gb", type=float, required=True,
                   help="storage budget for THIS cache; the emitted token count is "
                        "budget-gb * 1000 / mb-per-token")
    p.add_argument("--mb-per-token", type=float, default=MB_PER_TOKEN,
                   help=f"default {MB_PER_TOKEN}, measured from cache/rap_ego")
    p.add_argument("--data-root", type=Path,
                   default=Path(os.environ.get("HOME", "")) / "navsim")
    p.add_argument("--split", default="trainval")
    p.add_argument("--config-dir", type=Path,
                   default=Path("navsim/planning/script/config/common/train_test_split/scene_filter"))
    p.add_argument("--out", type=Path, default=None,
                   help="output yaml name; defaults to navtrain_<dataset>_fixed.yaml")
    p.add_argument("--index-path", type=Path, default=None)
    p.add_argument("--workers", type=int, default=8)
    p.add_argument("--reindex", action="store_true")
    p.add_argument("--seed", type=int, default=0)
    p.add_argument("--num-history-frames", type=int, default=4)
    p.add_argument("--num-future-frames", type=int, default=10)
    p.add_argument("--frame-interval", type=int, default=1)
    p.add_argument("--has-route", action="store_true",
                   help="both run_dataset_caching_*.sh pass has_route=false, so the "
                        "default here is false to match what the job will do")
    p.add_argument("--require-ego-counterpart", action="store_true",
                   help="keep only stems whose originating scene token is already in "
                        "--ego-cache, so every sampled scene has its ego pair cached")
    p.add_argument("--ego-cache", type=Path, default=Path("cache/rap_ego"))
    args = p.parse_args()

    root = args.data_root / DATASETS[args.dataset]
    cfg = (args.num_history_frames, args.num_future_frames,
           args.frame_interval, args.has_route)

    index_path = args.index_path or Path(f".cache_index_{args.dataset}_{args.split}.json")
    if index_path.exists() and not args.reindex:
        blob = json.loads(index_path.read_text())
        if tuple(blob["config"]) != cfg:
            raise SystemExit(
                f"{index_path} was built with window config {tuple(blob['config'])}, "
                f"but this run wants {cfg}. Re-run with --reindex."
            )
        index = blob["index"]
        print(f"loaded index {index_path}: {len(index):,} stems, "
              f"{sum(len(v) for v in index.values()):,} tokens")
    else:
        index = build_index(root, args.split, cfg, args.workers, index_path)

    if args.require_ego_counterpart:
        if not args.ego_cache.is_dir():
            raise SystemExit(f"--ego-cache {args.ego_cache} not found")
        ego = {tok.name
               for log in args.ego_cache.iterdir() if log.is_dir()
               for tok in log.iterdir() if tok.is_dir()}
        # The perturbed stem suffix is the originating navtrain token; for aug the
        # originating token is the first half of scene_token, which is not in the
        # filename, so this flag only narrows the perturbed set.
        before = len(index)
        index = {s: t for s, t in index.items() if s.rsplit("_", 1)[-1] in ego}
        print(f"--require-ego-counterpart: {before:,} -> {len(index):,} stems")
        if not index:
            raise SystemExit("no stems left; the originating tokens are not in the ego cache")

    available = sum(len(v) for v in index.values())
    target = int(args.budget_gb * 1000 / args.mb_per_token)
    if target >= available:
        print(f"budget {args.budget_gb:g} GB covers all {available:,} available tokens "
              f"(~{available * args.mb_per_token / 1000:.0f} GB); emitting all of them")

    # Sample whole stems, not loose tokens: filter_scenes opens a pkl only if its stem is
    # in log_names, so a stem contributes all or none of its tokens. Shuffling stems keeps
    # the subset unbiased with respect to load order.
    stems = sorted(index)
    random.Random(args.seed).shuffle(stems)

    picked_log_names, picked_tokens = [], []
    for stem in stems:
        if len(picked_tokens) >= target:
            break
        picked_log_names.append(stem)
        picked_tokens.extend(index[stem])
    picked_tokens = picked_tokens[:target]

    out = dict(
        _target_="navsim.common.dataclasses.SceneFilter",
        _convert_="all",
        num_history_frames=args.num_history_frames,
        num_future_frames=args.num_future_frames,
        frame_interval=args.frame_interval,
        has_route=args.has_route,
        max_scenes=None,
        log_names=sorted(picked_log_names),
        tokens=picked_tokens,
    )
    dest = args.config_dir / (args.out or f"navtrain_{args.dataset}_fixed.yaml")
    dest.write_text(
        HEADER.format(dataset=args.dataset, n=len(picked_tokens), avail=available,
                      frac=len(picked_tokens) / available,
                      gb=len(picked_tokens) * args.mb_per_token / 1000,
                      mb=args.mb_per_token, root=root, split=args.split)
        + yaml.safe_dump(out, default_flow_style=False, sort_keys=False)
    )
    print(f"\n  {dest}")
    print(f"  {len(picked_tokens):,} tokens over {len(picked_log_names):,} stems "
          f"~{len(picked_tokens) * args.mb_per_token / 1000:.0f} GB")


if __name__ == "__main__":
    main()
