"""Generate scene_filter configs that cap the RAP dataset cache at a storage budget.

The budget is split evenly across the three caches. run_training.py consumes all of the
ego cache but only perturbed_fraction / others_fraction of the other two, so those pools
hold more than one run uses -- that headroom is the point: raising either fraction later
draws on data already cached instead of forcing another caching pass.

Tokens are sampled at random rather than truncated: SceneFilter.max_scenes stops loading
once it hits its limit, which would bias the subset toward whichever logs load first.
"""

import argparse
import random
from pathlib import Path

import yaml

HEADER = """# GENERATED by scripts/training/make_cache_subsets.py -- do not edit by hand.
# {n:,} of {total:,} navtrain tokens ({frac:.1%}), budget share {gb:.0f} GB at {mb} MB/token.
"""


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--budget-gb", type=float, default=400.0)
    parser.add_argument("--mb-per-token", type=float, default=16.8,
                        help="measured size of one rap_feature.gz + targets; see --measure in run_dataset_caching.sh")
    parser.add_argument("--seed", type=int, default=0)
    parser.add_argument("--probe-tokens", type=int, default=200,
                        help="also emit navtrain_probe.yaml, a small head of the ego set used to "
                             "measure real MB/token and peak RSS before committing to the budget")
    parser.add_argument("--config-dir", type=Path,
                        default=Path("navsim/planning/script/config/common/train_test_split/scene_filter"))
    args = parser.parse_args()

    source = args.config_dir / "navtrain.yaml"
    base = yaml.safe_load(source.read_text())
    all_tokens = base["tokens"]
    total = len(all_tokens)

    # Equal shares. run_training.py only draws perturbed_fraction (0.1) and
    # others_fraction (0.05) of those two pools, so they are deliberately cached larger
    # than any single run consumes -- raising either fraction later then needs no
    # re-caching, it just draws more from what is already on disk.
    shares = {"ego": 1.0, "perturbed": 1.0, "others": 1.0}
    denom = sum(shares.values())
    ego_n = int(args.budget_gb * 1e9 / (args.mb_per_token * 1e6) / denom)

    rng = random.Random(args.seed)
    pool = all_tokens[:]
    rng.shuffle(pool)

    print(f"budget {args.budget_gb:.0f} GB at {args.mb_per_token} MB/token "
          f"-> {int(args.budget_gb * 1e9 / (args.mb_per_token * 1e6)):,} tokens total\n")

    for name, share in shares.items():
        n = max(1, int(ego_n * share))
        # ego takes the head of the shuffled pool; the augmented sets draw from that same
        # head so every perturbed/cross-agent sample has its ego counterpart cached too.
        tokens = pool[:n]
        out = dict(base)
        out["tokens"] = tokens
        dest = args.config_dir / f"navtrain_{name}.yaml"
        dest.write_text(
            HEADER.format(n=n, total=total, frac=n / total,
                          gb=n * args.mb_per_token / 1000, mb=args.mb_per_token)
            + yaml.safe_dump(out, default_flow_style=False, sort_keys=False)
        )
        print(f"  {dest.name:24s} {n:>7,} tokens  ~{n * args.mb_per_token / 1000:6.1f} GB")

    if args.probe_tokens:
        n = args.probe_tokens
        out = dict(base)
        out["tokens"] = pool[:n]   # head of the ego set, so the probe measures representative scenes
        dest = args.config_dir / "navtrain_probe.yaml"
        dest.write_text(
            HEADER.format(n=n, total=total, frac=n / total,
                          gb=n * args.mb_per_token / 1000, mb=args.mb_per_token)
            + yaml.safe_dump(out, default_flow_style=False, sort_keys=False)
        )
        print(f"  {dest.name:24s} {n:>7,} tokens  ~{n * args.mb_per_token / 1000:6.1f} GB   (measurement pass)")


if __name__ == "__main__":
    main()
