import os
import glob
import torch
import numpy as np
from torchvision import transforms
from PIL import Image
import pandas as pd
from tqdm import tqdm
import cv2
import json
import random
import matplotlib
import itertools
matplotlib.use('Agg')
# Model
from model import *
from fisher.fisher_utils import vmf_loss as fisher_NLL, fisher_CE, batch_torch_A_to_R, fisher_entropy
from utils import *
from utils import read_config
# Dataset
from torch.utils.data import Dataset, DataLoader
from visualization.visualizer import visualizer, show_pcd

# Process
import os, json, itertools, subprocess, tempfile
from types import SimpleNamespace

class InferenceVO:
    def __init__(self, root_path, save_path, weight, nprocess, frames_dir=None, depth_dir=None, save_name=None):
        self.root_path = root_path
        self.save_path = save_path # './results'
        self.weight = weight
        self.args = read_config()

        if frames_dir:
            scene = save_name or os.path.basename(os.path.normpath(frames_dir))
            self.args.inference_data = {'YouTube': {'YouTube': [scene]}}
            self.args.data_path['YouTube'] = frames_dir
            if depth_dir:
                self.args.depth_path['YouTube'] = depth_dir

            if scene not in self.args.data_intrinsics.get('YouTube', {}):
                # depth_processor.py's --images-dir/--depth-dir mode writes per-scene intrinsics
                # next to the depth-maps folder, e.g. <depth_dir_parent>/<scene>_intrs.json
                auto_intrs_path = os.path.join(os.path.dirname(depth_dir), f'{scene}_intrs.json') if depth_dir else None
                if auto_intrs_path and os.path.exists(auto_intrs_path):
                    with open(auto_intrs_path) as f:
                        scene_intrs = json.load(f)
                    self.args.data_intrinsics.setdefault('YouTube', {}).update(scene_intrs)
                    print(f"Loaded intrinsics for '{scene}' from {auto_intrs_path}")
                else:
                    raise ValueError(
                        f"No camera intrinsics for scene '{scene}'. Expected either an entry in "
                        f"args.data_intrinsics['YouTube']['{scene}'], or a file at "
                        f"{auto_intrs_path or '<depth_dir_parent>/<scene>_intrs.json'} "
                        f"(generated by depth_processor.py's --images-dir/--depth-dir mode)."
                    )

        self.inference_data = self.args.inference_data
        self.save_name = save_name or self.weight.split('/')[-1].split('.')[0]
        self.args.save_name = self.save_name

        # Make Dirs
        self.already = True
        for key in self.inference_data.keys():
            os.makedirs('{}/{}/{}/{}'.format(self.save_path, key, self.weight.split('/')[-2], self.save_name), exist_ok=True)
            # os.makedirs('{}/{}/{}/{}'.format(self.save_path, key, self.weight.split('/')[-2], self.save_name+'_gt'), exist_ok=True)  # unused: nothing writes ground-truth data here
            self.inference_data[key][key] = sorted(self.inference_data[key][key])

        # Check Not Exists
        import copy
        self.temporary = copy.deepcopy(self.inference_data)
        for key in self.inference_data.keys():
            idxes = []
            for idx, scene_id in enumerate(self.inference_data[key][key]):
                if not os.path.exists('{}/{}/{}/{}/{}'.format(self.save_path, key, self.weight.split('/')[-2], self.save_name, scene_id.zfill(3) + '.txt')) and not os.path.exists('{}/{}/{}/{}/{}'.format(self.save_path, key, self.weight.split('/')[-2], self.save_name, scene_id.zfill(2) + '.txt')):
                    self.already = False
                    idxes.append(idx)
            self.temporary[key][key] = []
            # fill remaining
            for idx in idxes:
                self.temporary[key][key].append(self.inference_data[key][key][idx])
        
        self.inference_data = copy.deepcopy(self.temporary)
        # Job Scheduling based on nprocess & inference_data
        self.scheduler = []
        for map, value in self.inference_data.items():
            for key, scenes in value.items():
                for s in scenes:
                    self.scheduler.append(({key: [s]}, self.args.data_path, self.args.depth_path, self.args.data_intrinsics))
        total_action = len(self.scheduler)
        budget = total_action // nprocess
        remainder = total_action % nprocess
        self.ranges = [(s, e) for s, e in zip([0]+list(itertools.accumulate([budget + (i<remainder) for i in range(nprocess)])), itertools.accumulate([budget + (i<remainder) for i in range(nprocess)]))]

    def _to_serializable(self, x):
        if hasattr(x, "__dict__"):
            try:
                return {k: self._to_serializable(v) for k, v in x.__dict__.items()}
            except Exception:
                return str(x)
        if isinstance(x, (list, tuple)):
            return [self._to_serializable(v) for v in x]
        if isinstance(x, dict):
            return {str(k): self._to_serializable(v) for k, v in x.items()}
        return x 

    def _pack_attributes(self):
        d = dict(self.__dict__)
        if "args" in d:
            a = d["args"]
            if hasattr(a, "__dict__"):
                d["args"] = {k: self._to_serializable(v) for k, v in a.__dict__.items()}
        return self._to_serializable(d)

    def launch_workers(self, run_py="my_inference_utils.py", devices=None, python_bin="python"):
        nprocess = len(self.ranges)
        if devices is None:
            devices = list(range(nprocess))
        if len(devices) < nprocess:
            q, r = divmod(nprocess, len(devices))
            devices = (devices * q) + devices[:r]

        os.makedirs(self.save_path, exist_ok=True)

        base_payload = self._pack_attributes()
        procs = []
        json_paths = []
        for rank, ((start, end), dev) in enumerate(zip(self.ranges, devices)):
            payload = dict(base_payload)
            payload["worker"] = {"rank": rank, "range": [start, end]}
            # write a per-worker config
            cfg_path = os.path.join(
                self.save_path,
                f"worker_cfg_rank{rank}_dev{dev}.json"
            )
            with open(cfg_path, "w", encoding="utf-8") as f:
                json.dump(payload, f, ensure_ascii=False, indent=2)

            env = os.environ.copy()
            env["CUDA_VISIBLE_DEVICES"] = str(dev)

            # Launch non-blocking (background) just like " & " in bash
            cmd = [python_bin, run_py, "--config", cfg_path]
            procs.append(subprocess.Popen(cmd, env=env))
            json_paths.append(cfg_path)
        return procs, json_paths
    


if __name__ == '__main__':
    import argparse
    import sys

    cli_parser = argparse.ArgumentParser()
    cli_parser.add_argument("--config", type=str, required=True)
    cli_parser.add_argument("--frames-dir", type=str, default=None,
                             help="Directory containing video frames directly (e.g. data/YTB/nightcrash/frames). "
                                  "Overrides the config's YouTube inference_data/data_path for this run.")
    cli_parser.add_argument("--depth-dir", type=str, default=None,
                             help="Directory containing the matching depth maps for --frames-dir. "
                                  "Required alongside --frames-dir unless the config already points at valid depth maps.")
    cli_parser.add_argument("--save-name", type=str, default=None,
                             help="Name for the output subfolder, e.g. 'nightcrash' -> "
                                  "results/YouTube/<weight_dir>/nightcrash/. Defaults to the checkpoint name.")
    cli_args, _ = cli_parser.parse_known_args()

    # InferenceVO's internal read_config() re-parses sys.argv for just --config,
    # so strip the extra flags above before it runs.
    sys.argv = [sys.argv[0], "--config", cli_args.config]

    root = './data'
    weights = './weights/OpenVO/openvo_nusc_gt'
    save_path = "./results"


    paths = os.listdir(weights)
    ## Manual
    paths = ['model_ep-022.pt']

    for path in paths:
        if not path.endswith('.pt'):
            continue
        print(f'------- {path} --------')
        weight = os.path.join(weights, path)
        ivo = InferenceVO(root_path=root, save_path=save_path, weight=weight, nprocess=1,
                           frames_dir=cli_args.frames_dir, depth_dir=cli_args.depth_dir,
                           save_name=cli_args.save_name) # 4
        if ivo.already == True: # already evaluated!
            continue
        procs, json_pths = ivo.launch_workers(run_py="src/my_inference_utils.py", devices=[0])  # returns Popen handles 4 || 0->(0,1,2,3)
        for p in procs:
            p.wait() # wait till finished!
        ## Visualize # toggle on
        # visualizer(ivo.inference_data, save_path, weight)
